language: golang
os: linux

env:
  - GO111MODULE=on

git:
  depth: 1

install: true

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)